// Auth api routes

### Register a new user
POST http://localhost:3000/common-api/register
Content-Type: application/json

{
    "firstName": "Priya",
    "lastName": "Reddy",
    "email": "test_instructor_mock@example.com",
    "password": "hashedPassword",
    "role": "INSTRUCTOR"
  }
### Login user
POST http://localhost:3000/common-api/login
Content-Type: application/json

{
    "email": "test_instructor_mock@example.com",
    "password": "123456"
}

### Logout user
POST http://localhost:3000/common-api/logout



// User api routes

### Enroll course
POST http://localhost:3000/user-api/enroll-course
Content-Type: application/json

{
    "courseId": "69b7cd4671b24b7980911200"
}

### Get user enrolled courses
GET http://localhost:3000/user-api/my-courses

### Get user profile
GET http://localhost:3000/user-api/profile

### Get all courses
GET http://localhost:3000/user-api/courses



// Instructure api routes

### Create course
POST http://localhost:3000/instructor-api/create-course
Content-Type: application/json

{
    "title": "Node.js and Express Masterclass",
    "description": "Build scalable backend applications using Node.js and Express.",
    "courseOutcomes": [
      "Create REST APIs",
      "Authentication with JWT",
      "Connect MongoDB",
      "Error handling"
    ],
    "category": "Backend Development",
    "courseLevel": "Intermediate",
    "content": [
      {
        "video": {
          "title": "Node.js Fundamentals",
          "description": "Understanding Node.js architecture.",
          "url": "https://example.com/node-intro.mp4"
        }
      },
      {
        "video": {
          "title": "Building REST APIs",
          "description": "Creating RESTful APIs with Express.",
          "url": "https://example.com/express-api.mp4"
        }
      }
    ]
}

### Get instructor courses
GET http://localhost:3000/instructor-api/my-courses

### Get single course
GET http://localhost:3000/instructor-api/course/69b7beda67d24e6ad410cf77


### Add lecture
POST http://localhost:3000/instructor-api/add-lecture/69b82c07dab115900834218a/69b82c07dab115900834218b
Content-Type: application/json

{
    "title": "Node.js Fundamentals",
    "description": "Understanding Node.js architecture.",
    "video": "https://example.com/node-intro.mp4"
}


### Delete section
DELETE http://localhost:3000/instructor-api/delete-section/69b82c07dab115900834218a/69b82c07dab115900834218b

### Delete lecture
DELETE http://localhost:3000/instructor-api/delete-lecture/69b82c07dab115900834218a/69b82c07dab115900834218d/69b82c07dab115900834218e
